services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/auth_db
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/code/app
    command: |
      sh -c "
        echo '✅ База данных готова (healthcheck passed)' &&
        echo '🗄️ Создание таблиц...' &&
        python -c 'from app.core.database import Base, engine; from app.models.user import User; Base.metadata.create_all(bind=engine); print(\"✅ Таблицы созданы!\")' &&
        echo '🚀 Запуск сервера...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: